### ISSUE TITLE
"Unknown error occured" when adding receiver manually via IP and port

### ISSUE THREAD

**Issue by Bluscream** [Xyaren/homeassistant-magentatv#293]
> Same issue here:
> 
> ![](https://i.imgur.com/Q90SPu4.png) 

 _Originally posted by @Bluscream in [#270](https://github.com/Xyaren/homeassistant-magentatv/issues/270#issuecomment-2708830861)_

**Comment by Xyaren** [comment]
Please use the issue template.
There is no way to identify the issue just based on a screenshot.

**Comment by Bluscream** [comment]
Would it be
```yaml
logger:
  default: info
  logs:
    custom_components.homeassistant-magentatv: debug
```
? the issue template only directs me to a generic logger doc page

**Comment by Xyaren** [comment]
You can enable debug logs on the integration page: 
[![Open your Home Assistant instance and show an integration.](https://my.home-assistant.io/badges/integration.svg)](https://my.home-assistant.io/redirect/integration/?domain=magentatv)

![Image](https://github.com/user-attachments/assets/5bccb561-fabf-4976-8228-956850585a02)

When you deactive the debug again, you will directly download a log file.

Alternatively enable debug logs via the config and reload/restart homeassistant.

```yml
logger:
  logs:
    custom_components.magentatv: debug
```

---
I'll add that to the template.
